version: '2'
services:
    cercardio-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/cercardio/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=cercardio
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
